apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgBHmQUr4WVznJkwLHfZ0CUs9wNOJ5K2OJlyBOYQ9EFPdYX+Oe/SeVa5hBj4/ToEJd+KWpGeDPpDZIG97azX3ohEzlxqsGPKdHsFkVwGtEWun1YSu4q02tAIDniLwsqjaXI1eiR0Sio4E0ZJ190yDqz1Sx7DHtPubMJWCaANUnbQL8LcwMGfOLjslSkfq5lNhUaobopnF/yB/BsUnhSlGvB47Rmv3YQer7UKembblHgQ3DqB82kPi0r7+HmqKt3Yj2pxw8hPiEoo1xGyFoY8KxRuXAbOrlCHzcP7XRHKf3A07algKnr5XM3BuIroTXg4k9GpFsEjhMAMxuTuthGgwJ08QWdZNBPJKUbI1W8o2UV4x5dWcQUb12V/Pd8VpT/DF+T0tkcNmCVoN7GbIMSRBFtZTtIr3GLzlgRHjerd5glQR2eQ7KqdYFunLiXv1VToHMI2GdtCfxIxMXFqePPK1ML3o2QFJOqVZUITIKaqoUuhLvyMjkHPzmR4bf6IBwez65GajeN++27J+6g6yougA0crXDh6h9fhntNAkNRKPdHDm95SDc0YFwK45bgB90mpoxxbRIh+Ulr8u71kiHaY52m7YDKg8Bpjxr6NasilZ/xmSYDdVhGMA3t0K7LmqcSjNUCXvqpsQ8dizNzLCsmI9dBdzFN+6g6VWKIC+m7xpBVToDXv03FxrIJmiDev/DThWVmBx2warFXs8HXvFDMfUbaX3+uMZtu8GeHG
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

